<?php

declare(strict_types=1);

namespace Keirontw\SyliusRelayPointPlugin\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

final class Configuration implements ConfigurationInterface
{
    /**
     * @psalm-suppress UnusedVariable
     */
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('keirontw_sylius_relay_point');
        $rootNode = $treeBuilder->getRootNode();

        $rootNode
            ->children()
                ->arrayNode('geocoding')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->enumNode('provider')
                            ->values(['addok', 'nominatim', 'google_maps', 'photon', 'custom'])
                            ->defaultValue('addok')
                            ->info('addok: French BAN, free, no key needed (recommended for France). nominatim: self-hosted OSM, international. google_maps: commercial worldwide. photon: self-hosted OSM, lightweight. custom: bring your own GeocodingProviderInterface service alias.')
                        ->end()
                        ->arrayNode('addok')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('url')
                                    ->defaultValue('https://api-adresse.data.gouv.fr/search/')
                                    ->info('Public French government endpoint (no key needed) or your self-hosted Addok instance.')
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('nominatim')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('url')
                                    ->defaultValue('https://nominatim.openstreetmap.org/search')
                                    ->info('URL of your self-hosted Nominatim instance. The public nominatim.openstreetmap.org forbids SaaS-style usage.')
                                ->end()
                                ->scalarNode('secret')->defaultNull()->end()
                                ->scalarNode('user_agent')->defaultValue('SyliusRelayPointPlugin')->end()
                                ->scalarNode('contact_email')->defaultNull()->end()
                            ->end()
                        ->end()
                        ->arrayNode('google_maps')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('api_key')
                                    ->defaultNull()
                                    ->info('Google Maps Geocoding API key. Required when provider is set to google_maps.')
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('photon')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('url')
                                    ->defaultNull()
                                    ->info('URL of your self-hosted Photon instance. Required when provider is set to photon.')
                                ->end()
                                ->scalarNode('lang')->defaultNull()->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('providers')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->arrayNode('mondial_relay')
                            ->canBeEnabled()
                            ->children()
                                ->scalarNode('account')
                                    ->isRequired()
                                    ->info('Mondial Relay Enseigne code.')
                                ->end()
                                ->scalarNode('password')
                                    ->isRequired()
                                    ->info('Mondial Relay private key.')
                                ->end()
                                ->arrayNode('shipping_method_codes')
                                    ->scalarPrototype()->end()
                                    ->defaultValue([])
                                    ->info('Sylius shipping method codes routed to this provider.')
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('chronopost')
                            ->canBeEnabled()
                            ->children()
                                ->scalarNode('account')
                                    ->isRequired()
                                    ->info('Chronopost account number (CHRONOPOST_ACCOUNT).')
                                ->end()
                                ->scalarNode('password')
                                    ->isRequired()
                                    ->info('Chronopost password (CHRONOPOST_PASSWORD).')
                                ->end()
                                ->arrayNode('shipping_method_codes')
                                    ->scalarPrototype()->end()
                                    ->defaultValue([])
                                    ->info('Sylius shipping method codes routed to Chronopost (e.g. pickup_france, pickup_germany).')
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('shop2shop')
                            ->canBeEnabled()
                            ->children()
                                ->scalarNode('account')
                                    ->isRequired()
                                    ->info('Shop2Shop account number. Shop2Shop uses the same Chronopost SOAP API but with separate credentials.')
                                ->end()
                                ->scalarNode('password')
                                    ->isRequired()
                                    ->info('Shop2Shop password.')
                                ->end()
                                ->arrayNode('shipping_method_codes')
                                    ->scalarPrototype()->end()
                                    ->defaultValue([])
                                    ->info('Sylius shipping method codes routed to Shop2Shop.')
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('colissimo')
                            ->canBeEnabled()
                            ->children()
                                ->scalarNode('account_number')
                                    ->isRequired()
                                    ->info('Colissimo account number (provided by La Poste).')
                                ->end()
                                ->scalarNode('password')
                                    ->isRequired()
                                    ->info('Colissimo password.')
                                ->end()
                                ->enumNode('filter_relay')
                                    ->values(['A', 'P', 'C'])
                                    ->defaultValue('A')
                                    ->info('A=all, P=relay points only, C=lockers (consignes) only.')
                                ->end()
                                ->arrayNode('shipping_method_codes')
                                    ->scalarPrototype()->end()
                                    ->defaultValue([])
                                    ->info('Sylius shipping method codes routed to Colissimo.')
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('inpost')
                            ->canBeEnabled()
                            ->children()
                                ->scalarNode('base_url')
                                    ->isRequired()
                                    ->info('InPost REST API base URL for your country. France: https://api.inpost.fr/v1/points  Poland: https://api-pl-points.easypack24.net/v1/points  UK: https://api.inpost.co.uk/v1/points')
                                ->end()
                                ->arrayNode('shipping_method_codes')
                                    ->scalarPrototype()->end()
                                    ->defaultValue([])
                                    ->info('Sylius shipping method codes routed to InPost.')
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('colis_prive')
                            ->canBeEnabled()
                            ->children()
                                ->scalarNode('login')
                                    ->isRequired()
                                    ->info('Colis Privé login (same credentials as the label generation SOAP).')
                                ->end()
                                ->scalarNode('password')
                                    ->isRequired()
                                    ->info('Colis Privé password.')
                                ->end()
                                ->arrayNode('shipping_method_codes')
                                    ->scalarPrototype()->end()
                                    ->defaultValue([])
                                    ->info('Sylius shipping method codes routed to Colis Privé relay points.')
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
            ->end()
        ;

        return $treeBuilder;
    }
}
